# Generated by Django 4.2.5 on 2024-12-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PublishPosition', '0001_initial'),
        ('UserAuth', '0001_initial'),
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_time', models.DateTimeField(verbose_name='最后申请时间')),
                ('create_time', models.DateTimeField(verbose_name='申请创建时间')),
                ('active_state', models.SmallIntegerField(choices=[(1, '已申请'), (0, '已取消')], default=1, verbose_name='申请状态')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.user', verbose_name='申请者')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PublishPosition.position', verbose_name='申请岗位')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.resume', verbose_name='上传的简历')),
            ],
        ),
    ]
