# Generated by Django 4.2.5 on 2024-12-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='私信发送时间')),
                ('read', models.SmallIntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='私信状态')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_from_user', to='UserAuth.user', verbose_name='发送者')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserMessage.message', verbose_name='回复至')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message_to_user', to='UserAuth.user', verbose_name='接收方')),
            ],
        ),
    ]
