# Generated by Django 4.2.5 on 2024-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('gender', models.SmallIntegerField(choices=[(1, '不愿透露'), (2, '男'), (3, '女')], default=1, verbose_name='性别')),
                ('hr_allowed', models.SmallIntegerField(choices=[(1, '无HR资格'), (2, 'HR资格申请中'), (3, '具有HR资格')], default=1, verbose_name='身份切换权限')),
                ('identity', models.SmallIntegerField(choices=[(1, '用户'), (2, 'HR'), (3, '管理员')], default=1, verbose_name='权限身份')),
                ('edu_ground', models.CharField(blank=True, max_length=30, verbose_name='学历')),
                ('school', models.CharField(blank=True, max_length=30, verbose_name='学校')),
                ('major', models.CharField(blank=True, max_length=30, verbose_name='专业')),
                ('excepting_position', models.CharField(blank=True, max_length=30, verbose_name='意向职位')),
                ('excepting_location', models.CharField(blank=True, max_length=30, verbose_name='意向地点')),
            ],
        ),
    ]
